#!/usr/bin/env python3
"""
Export the live avadigitalagency.com WordPress site to static HTML in this repo.

One-directional backup: WordPress is the source of truth. Running this
overwrites the pages/ and posts/ folders with the current live content and
regenerates manifest.json + the content table in README.md.

Usage:
    export WP_USER=... WP_APP_PASSWORD=...   # optional; enables drafts/private
    python3 export_wp.py

Requires only the Python standard library.
"""
import base64
import json
import os
import re
import sys
import urllib.request
from datetime import datetime, timezone

BASE = "https://avadigitalagency.com/wp-json/wp/v2"
ROOT = os.path.dirname(os.path.abspath(__file__))

# Which statuses to export. "publish" == exactly what's live. Add "draft" etc.
# by setting WP_STATUS (comma-separated). Auth is required for non-public statuses.
STATUS = os.environ.get("WP_STATUS", "publish")

WP_USER = os.environ.get("WP_USER")
WP_APP_PASSWORD = os.environ.get("WP_APP_PASSWORD")


def auth_header():
    # A browser-like UA is required; the site's WAF returns 406 without one.
    headers = {"User-Agent": "ava-website-export/1.0 (+https://avadigitalagency.com)"}
    if WP_USER and WP_APP_PASSWORD:
        token = base64.b64encode(
            f"{WP_USER}:{WP_APP_PASSWORD.replace(' ', '')}".encode()
        ).decode()
        headers["Authorization"] = f"Basic {token}"
    return headers


def fetch_all(endpoint):
    """Fetch every item from a paginated WP REST endpoint."""
    items, page = [], 1
    fields = "id,slug,link,title,content,modified,date,type,status"
    while True:
        url = (
            f"{BASE}/{endpoint}?per_page=100&page={page}"
            f"&status={STATUS}&_fields={fields}&orderby=slug&order=asc"
        )
        req = urllib.request.Request(url, headers=auth_header())
        try:
            with urllib.request.urlopen(req) as resp:
                batch = json.load(resp)
        except urllib.error.HTTPError as e:
            # WP returns 400 when page exceeds total pages -> we're done.
            if e.code == 400:
                break
            raise
        if not batch:
            break
        items.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    return items


def slugify(item):
    slug = item.get("slug") or f"id-{item['id']}"
    return re.sub(r"[^a-z0-9\-]", "-", slug.lower())


def write_item(folder, item):
    slug = slugify(item)
    title = item.get("title", {}).get("rendered", "").strip()
    body = item.get("content", {}).get("rendered", "")
    meta = {
        "id": item["id"],
        "slug": slug,
        "type": item.get("type"),
        "status": item.get("status"),
        "link": item.get("link"),
        "date": item.get("date"),
        "modified": item.get("modified"),
    }
    header = "<!-- ava-website export: source-of-truth is WordPress. Do not edit here. -->\n"
    header += "<!-- meta " + json.dumps(meta) + " -->\n"
    html = (
        f"{header}<!doctype html>\n<html lang=\"en\">\n<head>\n"
        f"<meta charset=\"utf-8\">\n<title>{title}</title>\n"
        f"<link rel=\"canonical\" href=\"{meta['link']}\">\n</head>\n<body>\n"
        f"<h1>{title}</h1>\n{body}\n</body>\n</html>\n"
    )
    path = os.path.join(ROOT, folder, f"{slug}.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return meta


def rewrite_folder(folder):
    """Clear old exported html so deletions on WP propagate to the backup."""
    d = os.path.join(ROOT, folder)
    os.makedirs(d, exist_ok=True)
    for name in os.listdir(d):
        if name.endswith(".html"):
            os.remove(os.path.join(d, name))


def main():
    print(f"Exporting live site (status={STATUS})...")
    pages = fetch_all("pages")
    posts = fetch_all("posts")
    print(f"  {len(pages)} pages, {len(posts)} posts")

    rewrite_folder("pages")
    rewrite_folder("posts")

    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": BASE,
        "status_filter": STATUS,
        "pages": [write_item("pages", p) for p in pages],
        "posts": [write_item("posts", p) for p in posts],
    }
    manifest["counts"] = {"pages": len(pages), "posts": len(posts)}

    with open(os.path.join(ROOT, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    update_readme(manifest)
    print(f"Done. manifest.json + README.md updated.")


def update_readme(manifest):
    stamp = manifest["generated_at"][:10]
    lines = [
        "# Ava Digital Agency — Website Backup",
        "",
        "**Automated one-directional export of the live WordPress site.**",
        "The live site at https://avadigitalagency.com is the source of truth.",
        "Files here are generated by `export_wp.py` — do not hand-edit them.",
        "",
        f"- **Last export:** {stamp}",
        f"- **Pages:** {manifest['counts']['pages']}  |  **Posts:** {manifest['counts']['posts']}",
        f"- **Status filter:** `{manifest['status_filter']}`",
        "",
        "## Refresh the backup",
        "```bash",
        "python3 export_wp.py   # WP_USER / WP_APP_PASSWORD optional (enables drafts)",
        "git add -A && git commit -m \"Backup live site\" && git push",
        "```",
        "",
        "## Contents",
        "- `pages/` — exported WordPress pages (one HTML file per page)",
        "- `posts/` — exported WordPress blog posts",
        "- `manifest.json` — full index with slugs, links, and modified dates",
        "- `archive/` — the previous hand-authored static files (superseded)",
        "",
        "_Each exported file keeps a `<!-- meta ... -->` header with its WP id,",
        "slug, canonical link, and last-modified date._",
    ]
    with open(os.path.join(ROOT, "README.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
